// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PhotoAlbum.Infrastructure.Persistence;

#nullable disable
// EF Core生成的迁移代码，描述了当前DbContext模型的结构和关系，
// 可当成数据库结构的快照，EF Core用它来生成迁移脚本
namespace PhotoAlbum.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260918115304_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("PhotoAlbum.Domain.Entities.Album", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CoverPhotoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Remark")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CoverPhotoId");

                    b.HasIndex("ParentId");

                    b.ToTable("photo_set", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "未分类"
                        });
                });

            modelBuilder.Entity("PhotoAlbum.Domain.Entities.Person", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("person", (string)null);
                });

            modelBuilder.Entity("PhotoAlbum.Domain.Entities.Photo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ImportTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OtherInfo")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoFilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Remark")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TakenTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Hash");

                    b.ToTable("photo", (string)null);
                });

            modelBuilder.Entity("PhotoAlbum.Domain.Entities.PhotoAlbumRelation", b =>
                {
                    b.Property<long>("PhotoId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("AlbumId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("INTEGER");

                    b.HasKey("PhotoId", "AlbumId");

                    b.HasIndex("AlbumId");

                    b.ToTable("photo_album", (string)null);
                });

            modelBuilder.Entity("PhotoAlbum.Domain.Entities.Album", b =>
                {
                    b.HasOne("PhotoAlbum.Domain.Entities.Photo", "CoverPhoto")
                        .WithMany()
                        .HasForeignKey("CoverPhotoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PhotoAlbum.Domain.Entities.Album", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CoverPhoto");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("PhotoAlbum.Domain.Entities.PhotoAlbumRelation", b =>
                {
                    b.HasOne("PhotoAlbum.Domain.Entities.Album", "Album")
                        .WithMany()
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhotoAlbum.Domain.Entities.Photo", "Photo")
                        .WithMany("PhotoAlbumRelations")
                        .HasForeignKey("PhotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("PhotoAlbum.Domain.Entities.Album", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("PhotoAlbum.Domain.Entities.Photo", b =>
                {
                    b.Navigation("PhotoAlbumRelations");
                });
#pragma warning restore 612, 618
        }
    }
}
